// Mock data for Maintain It Bandits LLC clone

export const COMPANY = {
  name: 'Maintain It Bandits LLC',
  tagline: 'CLEAN SPACES \u00b7 HEALTHY PLACES',
  category: 'Lawn Care Service',
  logo: 'https://customer-assets.emergentagent.com/job_bandits-replica/artifacts/46mb1ori_1B8C2EE3-.png',
  // NAP \u2014 (512) 518-1558 is primary. Update Google Business Profile to match.
  phone: '(512) 518-1558',
  phoneRaw: '5125181558',
  email: 'info@maintainitbandits.com',
  hours: 'Mon\u2013Fri: 7:00 AM \u2013 5:00 PM \u00b7 Sat: 9:00 AM \u2013 5:00 PM',
  hoursStructured: [
    { day: 'Monday', open: '07:00', close: '17:00' },
    { day: 'Tuesday', open: '07:00', close: '17:00' },
    { day: 'Wednesday', open: '07:00', close: '17:00' },
    { day: 'Thursday', open: '07:00', close: '17:00' },
    { day: 'Friday', open: '07:00', close: '17:00' },
    { day: 'Saturday', open: '09:00', close: '17:00' },
    { day: 'Sunday', open: null, close: null },
  ],
  area: 'Austin TX & Surrounding Areas',
  city: 'Austin',
  region: 'TX',
  country: 'US',
  // Credibility & trust info \u2014 update with your actual numbers
  founded: 2020,
  jobsCompleted: '2,500+',
  licenseNumber: 'TX-LLC-2020', // Update with your real LLC / license number
  insurance: 'General Liability & Workers\u2019 Comp',
  guarantee: '100% Satisfaction Guaranteed',
};

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Services', path: '/services', hasDropdown: 'services' },
  { label: 'Service Areas', path: '/service-areas', hasDropdown: 'areas' },
  { label: 'Gallery', path: '/gallery' },
  { label: 'Blog', path: '/blog' },
  { label: 'About', path: '/about' },
  { label: 'Contact', path: '/contact' },
];

export const SERVICES = [
  {
    slug: 'lawn-mowing',
    title: 'Lawn Mowing & Maintenance',
    short: 'Weekly & bi-weekly lawn mowing, edging, blowing, and trimming to keep your Austin TX property looking pristine year-round.',
    image: '/gallery/mower-action.jpg',
    description: 'Our lawn mowing and maintenance services are designed to keep your property looking its best year-round. We use professional-grade equipment and proven techniques to deliver a clean, even cut every time. Our team pays attention to the details - from precise edging along walkways to careful trimming around obstacles.',
    included: [
      'Weekly or bi-weekly mowing schedules',
      'Professional-grade equipment',
      'Precise edging and trimming',
      'Grass clipping cleanup',
      'Seasonal height adjustments',
      'Stripe patterns available',
    ],
    benefits: [
      'Consistent, professional appearance',
      'Healthier lawn growth',
      'Time savings for you',
      'Curb appeal improvement',
      'Flexible scheduling options',
    ],
  },
  {
    slug: 'landscaping',
    title: 'Landscaping & Design',
    short: 'Custom landscape design, garden bed installation, mulching, and hardscaping to transform your outdoor space in Austin TX.',
    image: '/gallery/crepe-myrtle-landscaping.jpg',
    description: 'Transform your outdoor space with our complete landscape design and installation services. From native plant gardens to hardscaping features, we create beautiful, low-maintenance landscapes tailored to the Austin climate.',
    included: [
      'Custom landscape design',
      'Garden bed installation',
      'Mulching & ground cover',
      'Hardscaping & stonework',
      'Native plant selection',
      'Irrigation planning',
    ],
    benefits: [
      'Increased property value',
      'Low maintenance solutions',
      'Water-wise designs',
      'Year-round curb appeal',
      'Custom to your style',
    ],
  },
  {
    slug: 'fertilization',
    title: 'Fertilization & Weed Control',
    short: 'Seasonal fertilization programs and targeted weed control to keep your Austin lawn green, healthy, and weed-free.',
    image: '/gallery/fresh-mow-stripes-after.jpg',
    description: 'A healthy lawn starts with proper nutrition and weed management. Our seasonal fertilization programs are tailored to Austin\u2019s climate and grass types, ensuring lush, green growth all year long.',
    included: [
      'Custom fertilization programs',
      'Pre-emergent weed control',
      'Post-emergent treatments',
      'Soil pH testing',
      'Grub & pest prevention',
      'Seasonal applications',
    ],
    benefits: [
      'Greener, thicker lawn',
      'Fewer weeds',
      'Stronger root system',
      'Drought resistance',
      'Long-term lawn health',
    ],
  },
  {
    slug: 'sod-installation',
    title: 'Sod Installation',
    short: 'Fresh sod installation with premium grass varieties suited for Austin TX climate \u2014 Bermuda, St. Augustine, and Zoysia.',
    image: '/gallery/service-sod-installation.jpg',
    description: 'Get an instant lawn with our professional sod installation service. We prepare the soil, install fresh sod, and provide care instructions so your new lawn thrives from day one.',
    included: [
      'Site preparation & grading',
      'Premium sod varieties',
      'Bermuda, St. Augustine, Zoysia',
      'Soil amendment',
      'Installation & rolling',
      'Aftercare guidance',
    ],
    benefits: [
      'Instant green lawn',
      'Erosion control',
      'Increased property value',
      'Varieties for shade or sun',
      'Professional results',
    ],
  },
  {
    slug: 'property-maintenance',
    title: 'Property Maintenance',
    short: 'Comprehensive residential and commercial property maintenance for Austin TX \u2014 keeping your entire property in top shape.',
    image: '/gallery/lush-lawn-after.jpg',
    description: 'From residential homes to commercial properties, we provide comprehensive maintenance services that keep every part of your property looking great and functioning properly.',
    included: [
      'Residential maintenance',
      'Commercial property care',
      'Seasonal cleanups',
      'Tree & shrub trimming',
      'Leaf removal',
      'Storm cleanup',
    ],
    benefits: [
      'One company for all needs',
      'Consistent appearance',
      'Reduced ownership stress',
      'Preventative care',
      'Reliable scheduling',
    ],
  },
  {
    slug: 'cleaning',
    title: 'Cleaning Services',
    short: 'Move-in cleaning, move-out cleaning, and rodent feces cleanup services for Austin TX homes. Thorough, safe, and reliable.',
    image: '/gallery/service-cleaning.jpg',
    description: 'Our professional cleaning services are perfect for move-in/move-out situations and specialty cleanups. We handle the dirty work so you can focus on what matters.',
    included: [
      'Move-in cleaning',
      'Move-out cleaning',
      'Deep cleaning',
      'Rodent feces cleanup',
      'Kitchen & bathroom focus',
      'Eco-friendly products',
    ],
    benefits: [
      'Spotless results',
      'Safe sanitization',
      'Time-saving',
      'Stress-free moves',
      'Trusted professionals',
    ],
  },
  {
    slug: 'mulching',
    title: 'Mulching',
    short: 'Professional mulch supply and installation for Austin TX garden beds. Retains moisture, suppresses weeds, and boosts curb appeal year-round.',
    image: '/gallery/service-mulching.jpg',
    description: 'Fresh mulch is one of the best investments you can make in your Austin landscape. It regulates soil temperature, locks in moisture through brutal Texas summers, suppresses weeds, and gives every bed a clean, finished look. We supply and install hardwood, cedar, pine bark, and specialty mulches.',
    included: [
      'Hardwood, cedar & pine bark mulch options',
      'Bed edging and cleanup before install',
      'Even 2-3 inch depth application',
      'Mulch kept clear of plant stems and trunks',
      'Debris removal after install',
      'One-time or seasonal refresh service',
    ],
    benefits: [
      'Retains soil moisture in Austin heat',
      'Suppresses weeds naturally',
      'Regulates soil temperature',
      'Improves curb appeal instantly',
      'Protects plant root systems',
    ],
  },
  {
    slug: 'shrub-trimming',
    title: 'Shrub & Hedge Trimming',
    short: 'Professional shrub and hedge trimming in Austin TX. We shape, prune, and maintain your bushes and hedges for a clean, healthy landscape year-round.',
    image: '/gallery/service-shrub-trimming.jpg',
    description: 'Overgrown shrubs and hedges drag down the appearance of even a well-maintained lawn. Our crew shapes and prunes ornamental shrubs, hedgerows, topiaries, and foundation plantings throughout the Austin area, keeping them healthy, correctly sized, and looking sharp.',
    included: [
      'Hand and power trimming of all shrub types',
      'Shaping and size reduction',
      'Deadwood and crossing branch removal',
      'Debris cleanup and haul-off',
      'One-time or recurring service available',
      'Advice on best pruning timing per species',
    ],
    benefits: [
      'Neat, polished property appearance',
      'Healthier plant growth',
      'Prevents overgrowth onto walkways',
      'Improves light and air circulation',
      'Extends the life of your plantings',
    ],
  },
  {
    slug: 'flower-bed-planting',
    title: 'Flower Bed Design & Planting',
    short: 'Custom flower bed design and installation in Austin TX. We create colorful, low-maintenance garden beds with plants suited for Central Texas.',
    image: '/gallery/service-mulching.jpg',
    description: 'A well-designed flower bed transforms the front or back of any Austin home. We design, install, and plant custom garden beds using flowering plants, ornamental grasses, and Austin-native species that thrive in Central Texas heat, clay soil, and variable rainfall.',
    included: [
      'Custom bed layout and design',
      'Soil prep and amendment',
      'Plant selection suited for Austin climate',
      'Full planting and installation',
      'Mulching after planting',
      'Seasonal color or perennial options',
    ],
    benefits: [
      'Dramatic curb appeal boost',
      'Plants chosen to survive Austin summers',
      'Low-maintenance native options available',
      'Increases property value',
      'Custom to your style and budget',
    ],
  },
  {
    slug: 'seasonal-cleanup',
    title: 'Seasonal Yard Cleanups',
    short: 'Spring and fall yard cleanup services in Austin TX. We clear leaves, debris, dead growth, and overgrowth so your property looks great every season.',
    image: '/gallery/lush-lawn-after.jpg',
    description: 'Austin yards need attention at the start and end of every growing season. Our seasonal cleanup crews clear out the buildup of leaves, dead plant material, winter debris, and overgrown areas, leaving your property fresh, clean, and ready for the season ahead.',
    included: [
      'Leaf removal and bagging',
      'Dead plant and debris removal',
      'Bed cleanouts and edging',
      'Overgrown shrub and grass trimming',
      'Debris haul-off included',
      'Spring and fall scheduling available',
    ],
    benefits: [
      'Property looks great year-round',
      'Prevents pest and disease buildup',
      'Prepares lawn for seasonal growth',
      'Saves hours of DIY labor',
      'One-time or recurring service',
    ],
  },
  {
    slug: 'yard-work',
    title: 'Yard Work',
    short: 'General yard work and maintenance for Austin TX homeowners. Mowing, edging, raking, trimming, and cleanup done right every time.',
    image: '/gallery/mower-action.jpg',
    description: 'Not every yard project fits neatly into one category. Our general yard work service covers all the tasks that pile up and eat your weekends. From mowing and edging to raking, blowing, trimming, and general cleanup, our crews handle it all for Austin homeowners and property managers.',
    included: [
      'Lawn mowing and edging',
      'String trimming around obstacles',
      'Raking and leaf cleanup',
      'Blowing of hard surfaces',
      'General debris removal',
      'One-time or recurring visits',
    ],
    benefits: [
      'Get your weekends back',
      'Consistent, reliable scheduling',
      'No job too big or too small',
      'Licensed and insured crew',
      'One call for everything',
    ],
  },
  {
    slug: 'mulch-rock-installation',
    title: 'Mulch & Rock Installation',
    short: 'Mulch and decorative rock installation in Austin TX. River rock, decomposed granite, and hardwood mulch installed to enhance and protect your landscape.',
    image: '/gallery/service-mulching.jpg',
    description: 'Ground cover is one of the most impactful and practical upgrades you can make to your Austin landscape. We install a wide range of materials including hardwood mulch, cedar mulch, river rock, decomposed granite, and decorative stone to protect your soil, reduce weeds, and dramatically improve curb appeal.',
    included: [
      'Hardwood and cedar mulch installation',
      'River rock and decorative stone',
      'Decomposed granite installation',
      'Weed barrier fabric installation',
      'Bed edging and prep work',
      'Material delivery and cleanup',
    ],
    benefits: [
      'Long-term weed suppression',
      'Low to zero maintenance options',
      'Drought-friendly ground cover',
      'Permanent and seasonal options',
      'Dramatic landscape transformation',
    ],
  },
  {
    slug: 'junk-haul-off',
    title: 'Junk & Brush Haul-Off',
    short: 'Fast junk and brush haul-off in Austin TX. We remove yard debris, brush piles, storm waste, and unwanted junk quickly with no mess left behind.',
    image: '/gallery/service-junk-haul-off.jpg',
    description: 'Yard waste, brush piles, storm debris, and unwanted junk pile up fast. Our haul-off crew loads everything up and removes it from your property quickly and cleanly. We serve homeowners, landlords, property managers, and anyone who needs a yard cleared fast in the Austin metro area.',
    included: [
      'Brush and limb pile removal',
      'Storm debris cleanup and haul-off',
      'Old yard waste and leaves',
      'Unwanted outdoor furniture and junk',
      'Full property clearing available',
      'Same-week service available',
    ],
    benefits: [
      'Fast, clean removal',
      'No mess left behind',
      'Saves time and truck rental cost',
      'Great for post-storm cleanup',
      'Handles what the city won\'t pick up',
    ],
  },
  {
    slug: 'pressure-washing',
    title: 'Pressure Washing',
    short: 'Professional pressure washing in Austin TX. We remove dirt, mold, mildew and grime from driveways, patios, fences and siding. Same-week service.',
    image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&q=80',
    description: 'Austin heat and humidity create the perfect conditions for algae, mold, and mildew to build up on your driveway, patio, walkways, fences, and siding. Our professional pressure washing service blasts years of buildup away fast, restoring surfaces to like-new condition. We use the right pressure and detergent for every surface type.',
    included: [
      'Concrete driveways and walkways',
      'Patios and pool decks',
      'Wood and vinyl fencing',
      'Brick and stone exterior walls',
      'Garage floors',
      'Soft wash option for delicate surfaces',
    ],
    benefits: [
      'Instant curb appeal boost',
      'Removes mold, mildew and algae',
      'Protects surfaces from long-term damage',
      'Safe for kids and pets after drying',
      'Same-week scheduling available',
    ],
  },
  {
    slug: 'gutter-cleaning',
    title: 'Gutter Cleaning',
    short: 'Professional gutter cleaning in Austin TX. We clear clogs, flush downspouts and protect your home from water damage. Free estimates.',
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=1200&q=80',
    description: 'Clogged gutters cause foundation damage, roof rot, and basement flooding - especially during Austin\'s heavy spring rain seasons. Our gutter cleaning crew removes all debris by hand, flushes every downspout, and checks for leaks and improper slope. Recommended twice a year for most Austin homes.',
    included: [
      'Hand removal of all debris from gutters',
      'Full downspout flush and check',
      'Inspection for leaks and improper slope',
      'Bag and haul-off all debris',
      'Single and two-story homes',
      'Twice-yearly service plans available',
    ],
    benefits: [
      'Prevents foundation damage',
      'Stops fascia board rot',
      'Eliminates mosquito breeding water',
      'Protects roof from water backup',
      'Peace of mind before rain season',
    ],
  },
];

export const SERVICE_AREAS = [
  { slug: 'austin', name: 'Austin TX' },
  { slug: 'round-rock', name: 'Round Rock TX' },
  { slug: 'cedar-park', name: 'Cedar Park TX' },
  { slug: 'georgetown', name: 'Georgetown TX' },
  { slug: 'pflugerville', name: 'Pflugerville TX' },
  { slug: 'leander', name: 'Leander TX' },
  { slug: 'bee-cave', name: 'Bee Cave TX' },
  { slug: 'west-lake-hills', name: 'West Lake Hills TX' },
  { slug: 'lakeway', name: 'Lakeway TX' },
  { slug: 'dripping-springs', name: 'Dripping Springs TX' },
  { slug: 'hutto', name: 'Hutto TX' },
  { slug: 'taylor', name: 'Taylor TX' },
];

export const TESTIMONIALS = [
  {
    text: 'Maintain It Bandits LLC transformed our yard completely! Their lawn mowing service is always on time and our grass has never looked better. Best lawn care in Austin!',
    name: 'Sarah M.',
    location: 'West Austin, TX',
  },
  {
    text: 'We switched from another Austin lawn service and the difference is night and day. Professional, reliable, and they actually care about doing quality work.',
    name: 'James R.',
    location: 'Round Rock, TX',
  },
  {
    text: 'Their landscaping design completely transformed our backyard. The team was knowledgeable about Austin-native plants and created something beautiful and low-maintenance.',
    name: 'Maria L.',
    location: 'Cedar Park, TX',
  },
];

export const HERO_IMAGE = '/gallery/lush-lawn-after.jpg';
export const AUSTIN_SKYLINE = 'https://images.unsplash.com/photo-1666969565832-b55bf42a900d?w=1200&q=80';
export const TEAM_IMAGE = '/gallery/mower-action.jpg';

export const WHY_CHOOSE = [
  'Licensed & insured for your peace of mind',
  'Reliable, on-time service every visit',
  'Consistent 5-star reviews from Austin homeowners',
  'Eco-friendly practices & Austin-native expertise',
  'Water-wise solutions for Central Texas climate',
  'Full-service \u2014 lawn care, landscaping, cleaning & more',
];

export const VALUES = [
  { title: 'Reliability', text: 'We show up on time, every time. You can count on us to deliver consistent, dependable service.' },
  { title: 'Quality', text: 'We never cut corners. Every job is completed to the highest standards with attention to detail.' },
  { title: 'Customer Focus', text: 'Your satisfaction is our priority. We listen, adapt, and go above and beyond to exceed expectations.' },
  { title: 'Community', text: "We're proud to be part of the Austin community and committed to making our neighborhoods beautiful." },
  { title: 'Sustainability', text: 'We use eco-friendly practices and products whenever possible to protect our environment.' },
  { title: 'Efficiency', text: 'We respect your time and property, completing work efficiently without sacrificing quality.' },
];

export const STATS = [
  { value: '500+', label: 'Happy Customers' },
  { value: '5', label: 'Star Rating' },
  { value: '12+', label: 'Service Areas' },
  { value: '7', label: 'Days a Week' },
];
